// <auto-generated />
namespace POS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DiscountModelMod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DiscountModelMod));
        
        string IMigrationMetadata.Id
        {
            get { return "201802140825127_DiscountModelMod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
