// <auto-generated />
namespace POS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201802071848205_ReModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
